version: '2'
services:
    mindspheredemo-app:
        image: mindspheredemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mindspheredemo-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=mindsphereDemo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mindspheredemo-mongodb:
        extends:
            file: mongodb.yml
            service: mindspheredemo-mongodb
